import mongoose from "mongoose"
import { config } from "dotenv"
import Inventory from "../lib/models/Inventory"

config() // Load .env.local

async function seed() {
  const uri = process.env.MONGODB_URI

  if (!uri) {
    throw new Error("❌ MONGODB_URI is not defined in the environment.")
  }

  await mongoose.connect(uri)
  await Inventory.deleteMany() // Reset

  await Inventory.insertMany([
    {
      id: "INV-001",
      item: "Teak Wood Planks",
      category: "Hardwood",
      quantity: 45,
      unit: "m³",
      minStock: 50,
      maxStock: 200,
      location: "Warehouse A-1",
      receivedDate: "2023-12-15",
      expiryDate: "2024-02-15",
      supplier: "Malaysian Timber Co.",
      costPerUnit: 850,
      status: "Low Stock",
    },
    {
      id: "INV-002",
      item: "Pine Wood Boards",
      category: "Softwood",
      quantity: 12,
      unit: "m³",
      minStock: 30,
      maxStock: 150,
      location: "Warehouse B-2",
      receivedDate: "2023-11-20",
      expiryDate: "2024-01-20",
      supplier: "Indonesian Wood Supply",
      costPerUnit: 420,
      status: "Expiring Soon",
    },
    {
      id: "INV-003",
      item: "Oak Wood Sheets",
      category: "Hardwood",
      quantity: 8,
      unit: "m³",
      minStock: 25,
      maxStock: 100,
      location: "Warehouse A-3",
      receivedDate: "2023-10-10",
      expiryDate: "2024-01-10",
      supplier: "Thai Forest Products",
      costPerUnit: 920,
      status: "Expired",
    },
    {
      id: "INV-004",
      item: "Bamboo Planks",
      category: "Sustainable",
      quantity: 85,
      unit: "m³",
      minStock: 40,
      maxStock: 120,
      location: "Warehouse C-1",
      receivedDate: "2024-01-05",
      expiryDate: "2024-04-05",
      supplier: "Vietnamese Lumber Ltd.",
      costPerUnit: 320,
      status: "Good",
    },
    {
      id: "INV-005",
      item: "Mahogany Boards",
      category: "Hardwood",
      quantity: 32,
      unit: "m³",
      minStock: 20,
      maxStock: 80,
      location: "Warehouse A-2",
      receivedDate: "2023-12-20",
      expiryDate: "2024-03-20",
      supplier: "Malaysian Timber Co.",
      costPerUnit: 1150,
      status: "Good",
    },
    {
      id: "INV-006",
      item: "Plywood Sheets",
      category: "Engineered",
      quantity: 15,
      unit: "m³",
      minStock: 25,
      maxStock: 100,
      location: "Warehouse B-1",
      receivedDate: "2023-11-15",
      expiryDate: "2024-02-15",
      supplier: "Indonesian Wood Supply",
      costPerUnit: 380,
      status: "Low Stock",
    },
    {
      id: "INV-007",
      item: "Cedar Planks",
      category: "Softwood",
      quantity: 28,
      unit: "m³",
      minStock: 25,
      maxStock: 100,
      location: "Warehouse B-3",
      receivedDate: "2023-12-01",
      expiryDate: "2024-03-01",
      supplier: "Canadian Wood Co.",
      costPerUnit: 650,
      status: "Good",
    },
    {
      id: "INV-008",
      item: "Birch Wood Panels",
      category: "Hardwood",
      quantity: 18,
      unit: "m³",
      minStock: 20,
      maxStock: 90,
      location: "Warehouse A-4",
      receivedDate: "2023-11-30",
      expiryDate: "2024-02-28",
      supplier: "Nordic Timber Ltd.",
      costPerUnit: 720,
      status: "Low Stock",
    },
    {
      id: "INV-009",
      item: "Rubber Wood Blocks",
      category: "Sustainable",
      quantity: 65,
      unit: "m³",
      minStock: 30,
      maxStock: 120,
      location: "Warehouse C-2",
      receivedDate: "2024-01-02",
      expiryDate: "2024-04-02",
      supplier: "Malaysian Timber Co.",
      costPerUnit: 280,
      status: "Good",
    },
    {
      id: "INV-010",
      item: "MDF Boards",
      category: "Engineered",
      quantity: 5,
      unit: "m³",
      minStock: 15,
      maxStock: 80,
      location: "Warehouse B-4",
      receivedDate: "2023-10-15",
      expiryDate: "2024-01-15",
      supplier: "Industrial Wood Co.",
      costPerUnit: 220,
      status: "Expired",
    },
    {
      id: "INV-011",
      item: "Acacia Wood Strips",
      category: "Hardwood",
      quantity: 42,
      unit: "m³",
      minStock: 35,
      maxStock: 110,
      location: "Warehouse A-5",
      receivedDate: "2023-12-10",
      expiryDate: "2024-03-10",
      supplier: "Vietnamese Lumber Ltd.",
      costPerUnit: 480,
      status: "Good",
    },
    {
      id: "INV-012",
      item: "Particle Board",
      category: "Engineered",
      quantity: 22,
      unit: "m³",
      minStock: 20,
      maxStock: 75,
      location: "Warehouse B-5",
      receivedDate: "2023-12-05",
      expiryDate: "2024-03-05",
      supplier: "Industrial Wood Co.",
      costPerUnit: 180,
      status: "Good",
    },
  ])

  console.log("✅ Inventory seeded!")
  await mongoose.disconnect()
}

seed();
